server:
  port: 80
#  servlet:
#    context-path: /cloud-consumer-order
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}